
### CLIENT CREDENTIALS FLOW
POST https://zinc-dotnet-test.auth.ap-southeast-2.amazoncognito.com/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=1bnpclv4mump6v8t90ajlpjiab&client_secret=bofe5uiogkk1bvhd7os28upu06nkacqb43og86mclmfsre0o21i&scope=zinc-dotnet-resource-svr/dotnet



### CLIENT CREDENTIALS FLOW
POST https://zincstoreglobal.auth.ap-southeast-2.amazoncognito.com/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=5dterc0gj38i80s81eiebk4bst&client_secret=b65doelo0uc3gqudupg9fqd2o7sel7smms1g4ljo433vpn7l380&scope=ZincStoreGlobal-Resource/api

