### PASSWORD GRANT FLOW
POST https://cognito-idp.ap-southeast-2.amazonaws.com/
Content-Type: application/x-amz-json-1.1
X-Amz-Target: AWSCognitoIdentityProviderService.InitiateAuth

{
    "AuthParameters" : {
        "USERNAME" : "hubertd@gmail.com",
        "PASSWORD" : "Test123!"
    },
    "AuthFlow" : "USER_PASSWORD_AUTH",
    "ClientId" : "55f5a6mpu0836rk8tk56uqdmt3"
}